version: '3.9'
services: 
  app:
    build: .
    ports: 
      - 8000:8000
  db:
    image: postgres:13.3
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_DB: catana_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes: 
      - db-postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - "80:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=example@example.com
      - PGADMIN_DEFAULT_PASSWORD=test
volumes: 
  db-postgres:
    external: true