USER_NAME_IS_EMPTY = "Username is empty"
EMAIL_IS_EMPTY = "E-mail is empty"
PASSWORD_IS_EMPTY = "Password is empty"
NAME_IS_EMPTY = "Name is empty"
SURNAME_IS_EMPTY = "Surname is empty"
PHONE_NUMBER_IS_EMPTY = "Phone number is empty"
